Name:           psacct-collector
Version:        0.1
Release:        3
Summary:        Program written in Python for collecting psacct information and storing it in a central repository

Group:		System Environment/Daemons
BuildArch: 	noarch
License:        GPL
Source0:        %{name}-%{version}.tar.gz

Requires:  	psacct
Requires:  	pyOpenSSL
Requires:  	python-kerberos
Requires:  	python-json
Requires:	pymongo

BuildRoot: 	/home/makerpm/rpmbuild/BUILDROOT

%description
The program is intended to collect all available data from files generated by the psacct package and send it to a central repository.
The only currently supported repository is a CouchDB database with Apache as a proxy using HTTP Negotiate as Kerberos authentication.
It is designed to be executed by cronjob. It disables accounting on default files. The data is collected from dump-acct command output.
NOTE: Because of the differences between dump-acct outputs on some systems there is a chance the code in not compatible with other distributions like Debian.This requires a somewhat minor change in the code and will be implemented in the future.
It is a modified version of OSG Gratia psacct probe software.

%prep
%setup 


%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{_sysconfdir}/cron.hourly
install -m 755 psacct_probe.cron.sh %{buildroot}%{_sysconfdir}/cron.hourly
mkdir -p %{buildroot}/opt/%{name}
cp -r * %{buildroot}/opt/%{name}
mkdir -p %{buildroot}%{_sysconfdir}/%{name}
install -m 644 collector.conf %{buildroot}%{_sysconfdir}/%{name}
mkdir -p %{buildroot}%{_sysconfdir}/logrotate.d
install -m 644 -t %{buildroot}%{_sysconfdir}/logrotate.d pscollector-logrotate

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc /opt/%{name}/README
%config %{_sysconfdir}/psacct-collector/collector.conf
%{_sysconfdir}/cron.hourly/psacct_probe.cron.sh
/opt/%{name}
%{_sysconfdir}/logrotate.d/pscollector-logrotate

%changelog

%post
wget http://peak.telecommunity.com/dist/ez_setup.py
python ez_setup.py
wget http://pypi.python.org/packages/2.6/C/CouchDB/CouchDB-0.8-py2.6.egg
easy_install CouchDB-0.8-py2.6.egg
rm -f ez_setup.py CouchDB-0.8-py2.6.egg

%postun
/sbin/accton
/sbin/accton /var/account/pacct
rm -f %{_sbindir}/psacct-collector

